### ISSUE TITLE
Getting back in the groove

### ISSUE THREAD

**Issue by AnnieShi** [AnnieShi/summer-html#1]
Hi Thomas,
I have finally begun to review material to get back in graphic design mode.
I have a few questions.
I kept the intro in the header.  Is this okay?
I divided the main into 3 sections instead of divs.  Sections or divs - which is best?
Finally, I wasn't sure if I should have opening hours as a <p> element or <dl>.
Please let me know anything else I might have missed or got incorrect.
I'll be practicing css next week.  
@thomasjbradley

**Comment by thomasjbradley** [comment]
I’m happy to see you’re practicing!

---

> I kept the intro in the header. Is this okay?

I think that’s okay if this is a single page website, but if there’s more than one page then I like to think of the contents of the header being the same on every page.

> I divided the main into 3 sections instead of divs. Sections or divs - which is best?

Sections definitely make sense semantically, but if you use a section it needs to have a heading inside it. So, “Traditional” should really be a heading.

> Finally, I wasn't sure if I should have opening hours as a ...

I’m not sure what elements you mean... you can wrap them in backticks to escape them.
Anyways: I would use a `<dl>` for the hours.

---

Other improvements I can see:
1. The e-mail address at the bottom should probably be linked.
2. The indentation of the `<dl>` tags inside each light bulb is too far, they should line up with the paragraph above.
